import "./globals.css";
import { ReactNode } from "react";
import Navbar from "./components/Navbar";
import { Work_Sans } from "next/font/google";


const workSans = Work_Sans({ subsets: ["latin"], variable: "--font-work-sans" });

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout ({children}: Readonly<{children: React.ReactNode}>) {
 return (
  <html lang="en" className={workSans.variable}>
      <body className="font-work-sans">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
    );


}